export const LOADING = "LOADING"; // статус загрузки, общий для всего приложения
export const ERROR = "ERROR"; // статус ошибки, общий для всего приложения
export const FETCH_ALARMS = "FETCH_ALARMS"; // получение списка будильников
export const CREATE_ALARM = "CREATE_ALARM"; // добавление нового будильника
export const TOGGLE_ALARM_STATUS = "TOGGLE_ALARM_STATUS"; // переключение статуса будильника
export const SORT_ALARMS_BY_STATUS = "SORT_ALARMS_BY_STATUS"; // сортировка по статусу
export const GET_ALARM_BY_ID = "GET_ALARM_BY_ID"; // получение данных выбранного будильника
export const EDIT_ALARM = "EDIT_ALARM"; // изменение выбранного будильника
export const REMOVE_ALARM = "REMOVE_ALARM"; // удаляем выбранный будильник
export const SORT_ALARMS_BY_NEXT_TRIGGER = "SORT_ALARMS_BY_NEXT_TRIGGER"; // сортируем по ближайшему будильнику
