export const FETCH_ALARMS_REQUEST = 'FETCH_ALARMS_REQUEST';
export const FETCH_ALARMS_SUCCESS = 'FETCH_ALARMS_SUCCESS';
export const FETCH_ALARMS_FAILURE = 'FETCH_ALARMS_FAILURE';

export const ADD_ALARM_REQUEST = 'ADD_ALARM_REQUEST';
export const ADD_ALARM_SUCCESS = 'ADD_ALARM_SUCCESS';
export const ADD_ALARM_FAILURE = 'ADD_ALARM_FAILURE';

export const UPDATE_ALARM_REQUEST = 'UPDATE_ALARM_REQUEST';
export const UPDATE_ALARM_SUCCESS = 'UPDATE_ALARM_SUCCESS';
export const UPDATE_ALARM_FAILURE = 'UPDATE_ALARM_FAILURE';

export const DELETE_ALARM_REQUEST = 'DELETE_ALARM_REQUEST';
export const DELETE_ALARM_SUCCESS = 'DELETE_ALARM_SUCCESS';
export const DELETE_ALARM_FAILURE = 'DELETE_ALARM_FAILURE';

export const SET_CURRENTLY_PLAYING_ALARM = 'SET_CURRENTLY_PLAYING_ALARM';
export const SORT_ALARMS = 'SORT_ALARMS';
